const rawdata = {
    
    data :[
            {
                heading : "Modi Seeks 'Forgiveness' From India's Poor Over Coronavirus Lockdown",
                imgurl : "img/news-img/news-30320a.png",
                detailurl : "news-30320a.html",
                region: "Asia",
                date : new Date("2020-3-30"),
            },
            {
                heading : "World Bank Warns Pandemic Will Hit Growth in Asia, China",
                imgurl : "img/news-img/news-31320d.png",
                detailurl : "news-31320d.html",
                region: "Asia",
                date : new Date("2020-3-31"),
            },
            {
                heading : "Indian Police Fire Tear Gas at Jobless Workers Defying Coronavirus Lockdown",
                imgurl : "img/news-img/news-31320a.png",
                detailurl : "news-31320a.html",
                region: "Asia",
                date : new Date("2020-3-31"),
            },
            {
                heading : "Vietnam PM Asks Major Cities to Prepare for Lockdown to Stop Virus",
                imgurl : "img/news-img/news-30320b.png",
                detailurl : "news-30320b.html",
                region: "Asia",
                date : new Date("2020-3-30"),
            },
            
            {
                heading : "COVID-19: ASEAN Must Act More Boldly",
                imgurl : "img/news-img/news-26320d.png",
                detailurl : "news-26320d.html",
                region: "Asia",
                date : new Date("2020-3-26"),
            },
            {
                heading : "Thailand Bans Entry to Foreigners, Prepares Emergency Measures Against Coronavirus",
                imgurl : "img/news-img/news-26320c.png",
                detailurl : "news-26320c.html",
                region: "Asia",
                date : new Date("2020-3-26"),
            },
            {
                heading : "China Reports Second Consecutive Day of No New Local Coronavirus Transmissions, Imported Cases Rise",
                imgurl : "img/news-img/news-26320b.png",
                detailurl : "news-26320b.html",
                region: "Asia",
                date : new Date("2020-3-26"),
            },
            {
                heading : "India Struggles with Coronavirus Shutdown; Pakistan Cases Top 1,000",
                imgurl : "img/news-img/news-26320a.png",
                detailurl : "news-26320a.html",
                region: "Asia",
                date : new Date("2020-3-26"),
            },
            {
                heading : "India to Lock Down Whole Country to Battle Coronavirus",
                imgurl : "img/news-img/news-25320c.png",
                detailurl : "news-25320c.html",
                region: "Asia",
                date : new Date("2020-3-25"),
            },
            {
                heading : "Thai Prime Minister to Invoke Emergency Powers as Virus Infections Climb",
                imgurl : "img/news-img/news-25320b.png",
                detailurl : "news-25320b.html",
                region: "Asia",
                date : new Date("2020-3-25"),
            },
            {
                heading : "One Fifth of American Companies in China Back to Normal Operations: Survey",
                imgurl : "img/news-img/news-25320a.png",
                detailurl : "news-25320a.html",
                region: "Asia",
                date : new Date("2020-3-25"),
            },
            {
                heading : "Malaysia Deploys Army as Coronavirus Measures Spread Across Southeast Asia",
                imgurl : "img/news-img/news-23320c.png",
                detailurl : "news-23320c.html",
                region: "Asia",
                date : new Date("2020-3-23"),
            },
            {
                heading : "Ex-Malaysian PM Mahathir Tested Negative for Coronavirus, Still Under Quarantine",
                imgurl : "img/news-img/news-23320b.png",
                detailurl : "news-23320b.html",
                region: "Asia",
                date : new Date("2020-3-23"),
            },
            {
                heading : "Hanoi Postpones ASEAN Leaders Summit Until Late June Amid Coronavirus Fears",
                imgurl : "img/news-img/news-20320f.png",
                detailurl : "news-20320f.html",
                region: "Asia",
                date : new Date("2020-3-20"),
            },
            {
                heading : "Amid Coronavirus, God Goes Online to Reach Worshippers",
                imgurl : "img/news-img/news-20320b.png",
                detailurl : "news-20320b.html",
                region: "Asia",
                date : new Date("2020-3-20"),
            },
            {
                heading : "Indonesia Should 'Prepare for the Worst' on Coronavirus, Red Cross Says",
                imgurl : "img/news-img/news-20320a.png",
                detailurl : "news-20320a.html",
                region: "Asia",
                date : new Date("2020-3-20"),
            },
            {
                heading : "Pandemic Makes Case for Partnership Between ROK and Myanmar, Other Mekong Nations",
                imgurl : "img/news-img/news-19320f.png",
                detailurl : "news-19320f.html",
                region: "Asia",
                date : new Date("2020-3-19"),
            },
            {
                heading : "China's Wuhan Reports No New Coronavirus Infections for First Time",
                imgurl : "img/news-img/news-19320c.png",
                detailurl : "news-19320c.html",
                region: "Asia",
                date : new Date("2020-3-19"),
            },
            {
                heading : "Coronavirus Surges Across SE Asia as Malaysia Warns of 'Tsunami' of Cases",
                imgurl : "img/news-img/news-19320b.png",
                detailurl : "news-19320b.html",
                region: "Asia",
                date : new Date("2020-3-19"),
            },
            {
                heading : "Coronavirus Compensation Promised to Poor Workers in India",
                imgurl : "img/news-img/news-19320a.png",
                detailurl : "news-19320a.html",
                region: "Asia",
                date : new Date("2020-3-19"),
            },
            {
                heading : "How a Mass Pilgrimage at a Malaysian Mosque Became a Coronavirus Hotspot",
                imgurl : "img/news-img/news-18320c.png",
                detailurl : "news-18320c.html",
                region: "Asia",
                date : new Date("2020-3-18"),
            },
            {
                heading : "In Slums and Windowless Apartments, Asia's Poor Bear Brunt of Coronavirus",
                imgurl : "img/news-img/news-18320a.png",
                detailurl : "news-18320a.html",
                region: "Asia",
                date : new Date("2020-3-18"),
            },
            {
                heading : "Coronavirus Closes India's Taj Mahal; Mumbai Tells Half Its Office Workers to Stay Home",
                imgurl : "img/news-img/news-17320b.png",
                detailurl : "news-17320b.html",
                region: "Asia",
                date : new Date("2020-3-17"),
            },
            {
                heading : "China Reports One Locally Transmitted Virus Case, 20 Imported Ones",
                imgurl : "img/news-img/news-17320a.png",
                detailurl : "news-17320a.html",
                region: "Asia",
                date : new Date("2020-3-17"),
            },
            {
                heading : "India Proposes Regional Fund to Fight Coronavirus as Cases Exceed 100",
                imgurl : "img/news-img/news-16320c.png",
                detailurl : "news-16320c.html",
                region: "Asia",
                date : new Date("2020-3-16"),
            },
            {
                heading : "French Infant Among Four New Coronavirus Cases in Cambodia",
                imgurl : "img/news-img/news-16320b.png",
                detailurl : "news-16320b.html",
                region: "Asia",
                date : new Date("2020-3-16"),
            },
            {
                heading : "BOJ Starts Moved-Up Policy Meeting After Fed's Rate Cut",
                imgurl : "img/news-img/news-16320a.png",
                detailurl : "news-16320a.html",
                region: "Asia",
                date : new Date("2020-3-16"),
            },
            {
                heading : "After Fleeing Abuse, Trafficked 'Brides' Stuck in China Due to Coronavirus",
                imgurl : "img/news-img/news-13320d.png",
                detailurl : "news-13320d.html",
                region: "Asia",
                date : new Date("2020-3-13"),
            },
            {
                heading : "Asia's Rapid Urbanization, Deforestation Linked to Deadly Viruses",
                imgurl : "img/news-img/news-12320e.png",
                detailurl : "news-12320e.html",
                region: "Asia",
                date : new Date("2020-3-12"),
            },
            {
                heading : "Some Businesses Allowed to Resume in Wuhan, Origin of Virus Outbreak",
                imgurl : "img/news-img/news-12320b.png",
                detailurl : "news-12320b.html",
                region: "Asia",
                date : new Date("2020-3-12"),
            },
            {
                heading : "WHO Declares Coronavirus a Pandemic as Cases Keep Rising Globally",
                imgurl : "img/news-img/news-12320a.png",
                detailurl : "news-12320a.html",
                region: "Asia",
                date : new Date("2020-3-12"),
            },
            {
                heading : "Japanese PM Calls for Event Cancellations for Another 10 Days to Prevent Spread of Virus",
                imgurl : "img/news-img/news-11320a.png",
                detailurl : "news-11320a.html",
                region: "Asia",
                date : new Date("2020-3-11"),
            },
            {
                heading : "WHO Chief Says Threat of Coronavirus Pandemic 'Very Real'",
                imgurl : "img/news-img/news-10320b.png",
                detailurl : "news-10320b.html",
                region: "Asia",
                date : new Date("2020-3-10"),
            },
            {
                heading : "Indian PM Cancels Dhaka Trip After Bangladesh Detects Coronavirus",
                imgurl : "img/news-img/news-10320a.png",
                detailurl : "news-10320a.html",
                region: "Asia",
                date : new Date("2020-3-10"),
            },
            {
                heading : "Chinese President Xi Postpones State Visit to Japan Amid Virus Outbreak",
                imgurl : "img/news-img/news-6320b.png",
                detailurl : "news-6320b.html",
                region: "Asia",
                date : new Date("2020-3-6"),
            },
            {
                heading : "South Korea Confirms 145 New Coronavirus Cases; Total Tops 5,700",
                imgurl : "img/news-img/news-5320b.png",
                detailurl : "news-5320b.html",
                region: "Asia",
                date : new Date("2020-3-5"),
            },
            {
                heading : "Coronavirus Cases Top 90,000 Worldwide: WHO Chief",
                imgurl : "img/news-img/news-4320a.png",
                detailurl : "news-4320a.html",
                region: "Asia",
                date : new Date("2020-3-4"),
            },
            {
                heading : "Japan, South Korea Among Countries of 'Greatest Concern' for Virus: WHO",
                imgurl : "img/news-img/news-3320c.png",
                detailurl : "news-3320c.html",
                region: "Asia",
                date : new Date("2020-3-3"),
            },
            {
                heading : "Malaysia's New PM Takes Office Amid Economic Challenges",
                imgurl : "img/news-img/news-3320b.png",
                detailurl : "news-3320b.html",
                region: "Asia",
                date : new Date("2020-3-3"),
            },
            {
                heading : "Indonesia Confirms First Cases of Coronavirus, Link to Japanese Visitor",
                imgurl : "img/news-img/news-3320a.png",
                detailurl : "news-3320a.html",
                region: "Asia",
                date : new Date("2020-3-3"),
            },
            {
                heading : "Pupils Should Stay Home While Japan Schools Closed Over Virus: Govt",
                imgurl : "img/news-img/news-28220c.png",
                detailurl : "news-28220c.html",
                region: "Asia",
                date : new Date("2020-2-28"),
            },
            {
                heading : "Indonesia Says Lack of Coronavirus Cases a Blessing From God",
                imgurl : "img/news-img/news-28220b.png",
                detailurl : "news-28220b.html",
                region: "Asia",
                date : new Date("2020-2-28"),
            },
            {
                heading : "Saudi Arabia Bars Pilgrims and Tourists Amid Coronavirus",
                imgurl : "img/news-img/news-28220a.png",
                detailurl : "news-28220a.html",
                region: "Asia",
                date : new Date("2020-2-28"),
            },
            {
                heading : "Pakistan Confirms First Coronavirus Cases",
                imgurl : "img/news-img/news-27220a.png",
                detailurl : "news-27220a.html",
                region: "Asia",
                date : new Date("2020-2-27"),
            },
            {
                heading : "North Koreans Told to Avoid Group Meals to Prevent Virus Spread",
                imgurl : "img/news-img/news-26220c.png",
                detailurl : "news-26220c.html",
                region: "Asia",
                date : new Date("2020-2-26"),
            },
            {
                heading : "Virus Deaths in China Top 2,700; Total Infection Cases Exceed 78,000",
                imgurl : "img/news-img/news-26220b.png",
                detailurl : "news-26220b.html",
                region: "Asia",
                date : new Date("2020-2-26"),
            },
            {
                heading : "Chinese Minister Blames Police Force for Prison Coronavirus Cases",
                imgurl : "img/news-img/news-26220a.png",
                detailurl : "news-26220a.html",
                region: "Asia",
                date : new Date("2020-2-26"),
            },
            {
                heading : "Coronavirus Deaths in China Top 2,600 as Hubei Records More Infections ",
                imgurl : "img/news-img/news-25220b.png",
                detailurl : "news-25220b.html",
                region: "Asia",
                date : new Date("2020-2-25"),
            },
            {
                heading : "China Bans Trade, Consumption of Wild Animals Due to Coronavirus",
                imgurl : "img/news-img/news-25220a.png",
                detailurl : "news-25220a.html",
                region: "Asia",
                date : new Date("2020-2-25"),
            },
            {
                heading : "South Korea on Alert After Surge in Coronavirus Cases",
                imgurl : "img/news-img/news-24220a.png",
                detailurl : "news-24220a.html",
                region: "Asia",
                date : new Date("2020-2-24"),
            },
            {
                heading : "South Korea Sees Surge in Coronavirus Cases",
                imgurl : "img/news-img/news-21220c.png",
                detailurl : "news-21220c.html",
                region: "Asia",
                date : new Date("2020-2-21"),
            },
            {
                heading : "China Says Media That 'Insults' the Country Must Pay a Price",
                imgurl : "img/news-img/news-21220b.png",
                detailurl : "news-21220b.html",
                region: "Asia",
                date : new Date("2020-2-21"),
            },
            {
                heading : "Vietnam Eases Border Trade Restrictions With China to Help Virus-Hit Businesses",
                imgurl : "img/news-img/news-21220a.png",
                detailurl : "news-21220a.html",
                region: "Asia",
                date : new Date("2020-2-21"),
            },
            {
                heading : "China Says Aerosol Infection Possible in Coronavirus Outbreak",
                imgurl : "img/news-img/news-20220a.png",
                detailurl : "news-20220a.html",
                region: "Asia",
                date : new Date("2020-2-20"),
            },
            {
                heading : "Sixty Myanmar Students to Be Evacuated From China as Coronavirus Spreads",
                imgurl : "img/news-img/news-27120b.png",
                detailurl : "news-27120b.html",
                region: "Yangon",
                date : new Date("2020-1-27"),
            },
            {
                heading : "China Nixes Myanmar's Plan to Evacuate 60 Students From Virus-Hit Wuhan",
                imgurl : "img/news-img/news-28120c.png",
                detailurl : "news-28120c.html",
                region: "Yangon",
                date : new Date("2020-1-28"),
            },
            {
                heading : "Korean Air Suspends Direct Flights Between Seoul, Yangon Due to Coronavirus",
                imgurl : "img/news-img/news-5320c.png",
                detailurl : "news-5320c.html",
                region: "Yangon",
                date : new Date("2020-3-5"),
            },
            {
                heading : "Bangkok Airways Suspends Most Flights to Myanmar as Virus Hits Air Travel",
                imgurl : "img/news-img/news-12320d.png",
                detailurl : "news-12320d.html",
                region: "Yangon",
                date : new Date("2020-3-12"),
            },
            {
                heading : "Myanmar 'On Waiting List' to Evacuate Students From Virus-Hit Wuhan",
                imgurl : "img/news-img/news-30120c.png",
                detailurl : "news-30120c.html",
                region: "Yangon",
                date : new Date("2020-1-30"),
            },
            {
                heading : "Myanmar Forms Central Committee to Coordinate Coronavirus Response",
                imgurl : "img/news-img/news-31120e.png",
                detailurl : "news-31120e.html",
                region: "Yangon",
                date : new Date("2020-1-31"),
            },
            {
                heading : "Suspected Chinese Coronavirus Patient in Stable Condition: Myanmar Hospital",
                imgurl : "img/news-img/news-31120g.png",
                detailurl : "news-31120g.html",
                region: "Yangon",
                date : new Date("2020-1-31"),
            },
            {
                heading : "Chinese Visitor to Myanmar Tests Negative for Coronavirus, Released After Four Days of Quarantine",
                imgurl : "img/news-img/news-3220d.png",
                detailurl : "news-3220d.html",
                region: "Yangon",
                date : new Date("2020-2-3"),
            },
            {
                heading : "Myanmar Suspends Visas-on-Arrival for Chinese Travelers Over Coronavirus",
                imgurl : "img/news-img/news-3220e.png",
                detailurl : "news-3220e.html",
                region: "Yangon",
                date : new Date("2020-2-3"),
            },
            {
                heading : "Myanmar Govt Asks Tour Operators to Suspend Travel Services for Chinese Visitors",
                imgurl : "img/news-img/news-3220f.png",
                detailurl : "news-3220f.html",
                region: "Yangon",
                date : new Date("2020-2-3"),
            },
            {
                heading : "Coronavirus Hits Myanmar's Travel Agents",
                imgurl : "img/news-img/news-4220c.png",
                detailurl : "news-4220c.html",
                region: "Yangon",
                date : new Date("2020-2-4"),
            },
            {
                heading : "Myanmar Maid Quarantined in Yangon After Boss in Singapore Infected With Coronavirus",
                imgurl : "img/news-img/news-10220d.png",
                detailurl : "news-10220d.html",
                region: "Yangon",
                date : new Date("2020-2-10"),
            },
            {
                heading : "Myanmar's Garment Factories Face Closure as Coronavirus Blocks Supplies",
                imgurl : "img/news-img/news-19220d.png",
                detailurl : "news-19220d.html",
                region: "Yangon",
                date : new Date("2020-2-19"),
            },
            {
                heading : "Myanmar Health Ministry Warns of Possible Coronavirus Outbreak as Global Toll Climbs",
                imgurl : "img/news-img/news-24220b.png",
                detailurl : "news-24220b.html",
                region: "Yangon",
                date : new Date("2020-2-24"),
            },
            {
                heading : "Myanmar Prisons to Educate Inmates on Coronavirus, Work on Prevention",
                imgurl : "img/news-img/news-26220d.png",
                detailurl : "news-26220d.html",
                region: "Yangon",
                date : new Date("2020-2-26"),
            },
            {
                heading : "Myanmar Govt Warns of Jail Time for Not Reporting Coronavirus Suspects",
                imgurl : "img/news-img/news-28220d.png",
                detailurl : "news-28220d.html",
                region: "Yangon",
                date : new Date("2020-2-28"),
            },
            {
                heading : "Myanmar Military Postpones Armed Forces Day Parade Over Coronavirus",
                imgurl : "img/news-img/news-3320d.png",
                detailurl : "news-3320d.html",
                region: "Yangon",
                date : new Date("2020-3-3"),
            },
            {
                heading : "11 Factories in Myanmar Close Due to Lack of Orders, Raw Materials",
                imgurl : "img/news-img/news-4320c.png",
                detailurl : "news-4320c.html",
                region: "Yangon",
                date : new Date("2020-3-4"),
            },
            {
                heading : "Myanmar Prepared to Ease Coronavirus Impact on Economy: Suu Kyi",
                imgurl : "img/news-img/news-11320c.png",
                detailurl : "news-11320c.html",
                region: "Yangon",
                date : new Date("2020-3-11"),
            },
            {
                heading : "Myanmar Govt Cancels Mass Gatherings and Thingyan Water Festival as Coronavirus Precaution",
                imgurl : "img/news-img/news-13320b.png",
                detailurl : "news-13320b.html",
                region: "Yangon",
                date : new Date("2020-3-13"),
            },
            {
                heading : "Tourist Arrivals in Myanmar Will Drop 50% Over COVID-19: Tourism Ministry",
                imgurl : "img/news-img/news-13320c.png",
                detailurl : "news-13320c.html",
                region: "Yangon",
                date : new Date("2020-3-13"),
            },
            {
                heading : "Myanmar Orders Quarantine, Monitoring for Arrivals from Countries Hit by Coronavirus",
                imgurl : "img/news-img/news-16320d.png",
                detailurl : "news-16320d.html",
                region: "Yangon",
                date : new Date("2020-3-16"),
            },
            {
                heading : "Myanmar Preschools Braced for Coronavirus Closures",
                imgurl : "img/news-img/news-16320f.png",
                detailurl : "news-16320f.html",
                region: "Yangon",
                date : new Date("2020-3-16"),
            },
            {
                heading : "The Myanmar Govt Has Been Spared a Real Test on Coronavirus—but No One's Luck Lasts Forever",
                imgurl : "img/news-img/news-16320g.png",
                detailurl : "news-16320g.html",
                region: "Yangon",
                date : new Date("2020-3-16"),
            },
            {
                heading : "RCSS Dialogue with Shan Residents Postponed Over Myanmar's Coronavirus Concerns",
                imgurl : "img/news-img/news-17320c.png",
                detailurl : "news-17320c.html",
                region: "Yangon",
                date : new Date("2020-3-17"),
            },
            {
                heading : "Myanmar Govt Suspends Advance Tax on Exports to Aid Virus-Hit Businesses",
                imgurl : "img/news-img/news-17320d.png",
                detailurl : "news-17320d.html",
                region: "Yangon",
                date : new Date("2020-3-17"),
            },
            {
                heading : "Myanmar-Based Diplomats Told to Cancel Events Amid Coronavirus Fears",
                imgurl : "img/news-img/news-17320f.png",
                detailurl : "news-17320f.html",
                region: "Yangon",
                date : new Date("2020-3-17"),
            },
            {
                heading : "Myanmar's Churches Close, Scale Back Easter Services to Prevent Coronavirus",
                imgurl : "img/news-img/news-18320d.png",
                detailurl : "news-18320d.html",
                region: "Yangon",
                date : new Date("2020-3-18"),
            },
            {
                heading : "UK Embassy Tells Citizens to Leave Myanmar Amid Coronavirus Concerns",
                imgurl : "img/news-img/news-18320e.png",
                detailurl : "news-18320e.html",
                region: "Yangon",
                date : new Date("2020-3-18"),
            },
            {
                heading : "Myanmar Unveils $70-Million Stimulus Package to Ease Economic Blow From Virus",
                imgurl : "img/news-img/news-19320d.png",
                detailurl : "news-19320d.html",
                region: "Yangon",
                date : new Date("2020-3-19"),
            },
            {
                heading : "Myanmar Closes All Land Borders to Foreigners",
                imgurl : "img/news-img/news-19320e.png",
                detailurl : "news-19320e.html",
                region: "Yangon",
                date : new Date("2020-3-19"),
            },
            {
                heading : "Combating Fake News in the Time of Coronavirus in Myanmar",
                imgurl : "img/news-img/news-20320c.png",
                detailurl : "news-20320c.html",
                region: "Yangon",
                date : new Date("2020-3-20"),
            },
            {
                heading : "Foreign Arrivals to Thailand Require Medical Certificate, $100K Insurance for COVID-19",
                imgurl : "img/news-img/news-20320d.png",
                detailurl : "news-20320d.html",
                region: "Yangon",
                date : new Date("2020-3-20"),
            },
            {
                heading : "Myanmar's Military Braced for Coronavirus Outbreak: Spokesman",
                imgurl : "img/news-img/news-23320d.png",
                detailurl : "news-23320d.html",
                region: "Yangon",
                date : new Date("2020-3-23"),
            },
            {
                heading : "Myanmar Prepares Quarantine Centers as Official COVID-19 Count Remains at Zero",
                imgurl : "img/news-img/news-23320f.png",
                detailurl : "news-23320f.html",
                region: "Yangon",
                date : new Date("2020-3-23"),
            },
            {
                heading : "Myanmar to Deport 86 Chinese Migrants for Illegal Residency After Yangon Bust",
                imgurl : "img/news-img/news-23320f.png",
                detailurl : "news-23320g.html",
                region: "Yangon",
                date : new Date("2020-3-23"),
            },
            {
                heading : "Myanmar reports first cases of coronavirus",
                imgurl : "img/news-img/news-24320a.png",
                detailurl : "news-24320a.html",
                region: "Yangon",
                date : new Date("2020-3-24"),
            },
            {
                heading : "Yangon Minister Quarantined After Coronavirus Contact",
                imgurl : "img/news-img/news-24320b.png",
                detailurl : "news-24320b.html",
                region: "Yangon",
                date : new Date("2020-3-24"),
            },
            {
                heading : "Myanmar Universities Suspend Exams as First COVID-19 Cases Confirmed",
                imgurl : "img/news-img/news-24320c.png",
                detailurl : "news-24320c.html",
                region: "Yangon",
                date : new Date("2020-3-24"),
            },
            {
                heading : "Myanmar Health Ministry: Both Coronavirus Patients Stable",
                imgurl : "img/news-img/news-24320d.png",
                detailurl : "news-24320d.html",
                region: "Yangon",
                date : new Date("2020-3-24"),
            },
            {
                heading : "Myanmar to Quarantine Arrivals from All Countries Over COVID-19",
                imgurl : "img/news-img/news-24320e.png",
                detailurl : "news-24320e.html",
                region: "Yangon",
                date : new Date("2020-3-24"),
            },
            {
                heading : "Suu Kyi Consoles Myanmar People Amid COVID-19, Stresses Health Guidelines, Calm",
                imgurl : "img/news-img/news-24320h.png",
                detailurl : "news-24320h.html",
                region: "Yangon",
                date : new Date("2020-3-24"),
            },
            {
                heading : "Myanmar Central Bank Cuts Interest Rates Another 1% to Aid Economy",
                imgurl : "img/news-img/news-25320d.png",
                detailurl : "news-25320d.html",
                region: "Yangon",
                date : new Date("2020-3-25"),
            },
            {
                heading : "Myanmar Confirms Third COVID-19 Case",
                imgurl : "img/news-img/news-25320e.png",
                detailurl : "news-25320e.html",
                region: "Yangon",
                date : new Date("2020-3-25"),
            },
            {
                heading : "Myanmar's Central Bank Says Banking Will Continue Despite Coronavirus",
                imgurl : "img/news-img/news-25320f.png",
                detailurl : "news-25320f.html",
                region: "Yangon",
                date : new Date("2020-3-25"),
            },
            {
                heading : "Myanmar Speaker Rejects Call to Summon Military-Majority Security Council to Address COVID-19",
                imgurl : "img/news-img/news-25320h.png",
                detailurl : "news-25320h.html",
                region: "Yangon",
                date : new Date("2020-3-25"),
            },
            {
                heading : "Myanmar Orders Half of Govt Employees to Stay Home Over COVID-19",
                imgurl : "img/news-img/news-26320e.png",
                detailurl : "news-26320e.html",
                region: "Yangon",
                date : new Date("2020-3-6"),
            },
            {
                heading : "Myanmar Confirms Two New COVID-19 Cases",
                imgurl : "img/news-img/news-27320a.png",
                detailurl : "news-27320a.html",
                region: "Yangon",
                date : new Date("2020-3-27"),
            },
            {
                heading : "Apartment Blocks Under Quarantine After Myanmar Finds Two More COVID-19 Cases",
                imgurl : "img/news-img/news-27320b.png",
                detailurl : "news-27320b.html",
                region: "Yangon",
                date : new Date("2020-3-27"),
            },
            {
                heading : "Myanmar Counts Three New Coronavirus Cases in Naypyitaw and Yangon",
                imgurl : "img/news-img/news-28320a.png",
                detailurl : "news-28320a.html",
                region: "Yangon",
                date : new Date("2020-3-28"),
            },
            {
                heading : "Myanmar Bans Incoming Commercial Flights to Tackle COVID-19",
                imgurl : "img/news-img/news-30320e.png",
                detailurl : "news-30320e.html",
                region: "Yangon",
                date : new Date("2020-3-30"),
            },
            {
                heading : "Myanmar Military Gives Support to Religious Leaders, Govt on COVID-19 Prevention",
                imgurl : "img/news-img/news-30320g.png",
                detailurl : "news-30320g.html",
                region: "Yangon",
                date : new Date("2020-3-30"),
            },
            {
                heading : "Myanmar Govt Announces Loan Package for Coronavirus-Hit Businesses in Key Sectors",
                imgurl : "img/news-img/news-30320i.png",
                detailurl : "news-30320i.html",
                region: "Yangon",
                date : new Date("2020-3-30"),
            },
            {
                heading : "Myanmar Reports Four New COVID-19 Cases; Total Climbs to 14",
                imgurl : "img/news-img/news-30320j.png",
                detailurl : "news-30320j.html",
                region: "Yangon",
                date : new Date("2020-3-30"),
            },
            {
                heading : "Myanmar Forms Civil-Military Emergency Task Force to Boost COVID-19 Response",
                imgurl : "img/news-img/news-31320b.png",
                detailurl : "news-31320b.html",
                region: "Yangon",
                date : new Date("2020-3-31"),
            },
            {
                heading : "As COVID-19 Arrives in Myanmar, Individual Responsibility, Competent Leadership Needed",
                imgurl : "img/news-img/news-31320e.png",
                detailurl : "news-31320e.html",
                region: "Yangon",
                date : new Date("2020-3-31"),
            },
            {
                heading : "Myanmar's Nurses, Doctors Face Eviction as Landlords Panic Over COVID-19",
                imgurl : "img/news-img/news-26320f.png",
                detailurl : "news-26320f.html",
                region: "Mandalay",
                date : new Date("2020-3-26"),
            },
            {
                heading : "Health Certificates Required to Enter Mandalay Religious Sites as Myanmar Struggles With COVID-19",
                imgurl : "img/news-img/news-30320f.png",
                detailurl : "news-30320f.html",
                region: "Mandalay",
                date : new Date("2020-3-30"),
            },
            {
                heading : "Naypyitaw Health Bosses Hopeful COVID-19 Under Control in Myanmar's Capital",
                imgurl : "img/news-img/news-30320h.png",
                detailurl : "news-30320h.html",
                region: "Mandalay",
                date : new Date("2020-3-30"),
            },
            {
                heading : "Amid Chinese Flu Fears, Mandalay Goes Without Masks While Dealers Make Profits",
                imgurl : "img/news-img/news-30120d.png",
                detailurl : "news-30120d.html",
                region: "Mandalay",
                date : new Date("2020-1-30"),
            },
            {
                heading : "Wuhan Flights to Myanmar Stopped Amid Coronavirus Outbreak",
                imgurl : "img/news-img/news-24120c.png",
                detailurl : "news-24120c.html",
                region: "Mandalay",
                date : new Date("2020-1-24"),
            },
            {
                heading : "Mandalay to Screen Chinese Visitors Amid Coronavirus Scare",
                imgurl : "img/news-img/news-31120f.png",
                detailurl : "news-31120f.html",
                region: "Mandalay",
                date : new Date("2020-1-31"),
            },
            {
                heading : "Myanmar Evacuates 59 Students From Virus-Hit Wuhan, China",
                imgurl : "img/news-img/news-2220a.png",
                detailurl : "news-2220a.html",
                region: "Mandalay",
                date : new Date("2020-2-20"),
            },
            {
                heading : "Myanmar Tour Guides Object to Granting Entry to Chinese Tourists With Health Notes",
                imgurl : "img/news-img/news-17220c.png",
                detailurl : "news-17220c.html",
                region: "Mandalay",
                date : new Date("2020-2-17"),
            },
            {
                heading : "Myanmar State Counselor's Public Meetings Draw Criticism Amid Coronavirus Fears",
                imgurl : "img/news-img/news-11320b.png",
                detailurl : "news-11320b.html",
                region: "Mandalay",
                date : new Date("2020-3-11"),
            },
            {
                heading : "Myanmar Bans Beach Tours Amid COVID-19",
                imgurl : "img/news-img/news-24320f.png",
                detailurl : "news-24320f.html",
                region: "Ayeyarwady",
                date : new Date("2020-3-24"),
            },
            {
                heading : "Bridegroom Arrested for Throwing Wedding Party Amid Ban on Public Gatherings in Myanmar",
                imgurl : "img/news-img/news-30320d.png",
                detailurl : "news-30320d.html",
                region: "Sagaing",
                date : new Date("2020-3-30"),
            },
            {
                heading : "Indian Govt Shuts Key Border Trade Gate with Myanmar Over Coronavirus Fears",
                imgurl : "img/news-img/news-10320c.png",
                detailurl : "news-10320c.html",
                region: "Sagaing",
                date : new Date("2020-3-10"),
            },
            {
                heading : "Myanmar Garment Factory Closes As COVID-19 Cuts Supplies",
                imgurl : "img/news-img/news-4320b.png",
                detailurl : "news-4320b.html",
                region: "Ayeyarwady",
                date : new Date("2020-3-4"),
            },
            {
                heading : "Thailand to Shut One of Two Border Crossings With Myanmar Amid COVID-19 Concerns",
                imgurl : "img/news-img/news-20320e.png",
                detailurl : "news-20320e.html",
                region: "Kayin",
                date : new Date("2020-3-20"),
            },
            {
                heading : "Myanmar Migrants in Thailand Discouraged From New Year Homecoming Amid Covid-19 Concerns",
                imgurl : "img/news-img/news-16320e.png",
                detailurl : "news-16320e.html",
                region: "Kayin",
                date : new Date("2020-3-16"),
            },
            {
                heading : "Border Gate Forced to Open as Myanmar Migrant Workers Leave Thailand Amid COVID-19",
                imgurl : "img/news-img/news-24320i.png",
                detailurl : "news-24320i.html",
                region: "Kayin",
                date : new Date("2020-3-24"),
            },
            {
                heading : "Myanmar Told to Brace for Major COVID-19 Outbreak as Returning Migrant Among New Cases",
                imgurl : "img/news-img/news-30320c.png",
                detailurl : "news-30320c.html",
                region: "Kayin",
                date : new Date("2020-3-30"),
            },
            {
                heading : "Thai Border Closures Over COVID-19 Spark Myanmar Migrants Return, Health Concerns",
                imgurl : "img/news-img/news-23320e.png",
                detailurl : "news-23320e.html",
                region: "Kayin",
                date : new Date("2020-3-23"),
            },
            {
                heading : "Myanmar Imposes Community Quarantines After COVID-19 Patient Visit",
                imgurl : "img/news-img/news-24320g.png",
                detailurl : "news-24320g.html",
                region: "Chin",
                date : new Date("2020-3-24"),
            },
            {
                heading : "With COVID-19 Confirmed Case, Myanmar's Chin State Makes Urgent Appeal for Protective Equipment",
                imgurl : "img/news-img/news-25320g.png",
                detailurl : "news-25320g.html",
                region: "Chin",
                date : new Date("2020-3-25"),
            },
            {
                heading : "Myanmar Medics Volunteer to Combat COVID-19 Menace",
                imgurl : "img/news-img/news-26320g.png",
                detailurl : "news-26320g.html",
                region: "Chin",
                date : new Date("2020-3-26"),
            },
            {
                heading : "Mon State MPs Urge Govt: Ban Pilgrimages to Myanmar's Golden Rock Over COVID-19",
                imgurl : "img/news-img/news-17320e.png",
                detailurl : "news-17320e.html",
                region: "Mon",
                date : new Date("2020-3-17"),
            },
            {
                heading : "A Fierce Battle in Western Myanmar Has Killed Hundreds as the Country Braces for COVID",
                imgurl : "img/news-img/news-25320i.png",
                detailurl : "news-25320i.html",
                region: "Rakhine",
                date : new Date("2020-3-25"),
            },
            {
                heading : "Amid Coronavirus Fears, Two Feverish Workers Quarantined at Myanmar-China Border",
                imgurl : "img/news-img/news-27120c.png",
                detailurl : "news-27120c.html",
                region: "Shan",
                date : new Date("2020-1-27"),
            },
            {
                heading : "With Virus-Hit China 'Closed for Business', Myanmar Exporters Feel the Pinch",
                imgurl : "img/news-img/news-11220d.png",
                detailurl : "news-11220d.html",
                region: "Shan",
                date : new Date("2020-2-11"),
            },
            {
                heading : "Myanmar Deports Chinese Coronavirus Suspect While Hunting Another Four",
                imgurl : "img/news-img/news-7220c.png",
                detailurl : "news-7220c.html",
                region: "Shan",
                date : new Date("2020-2-7"),
            },
            {
                heading : "Myanmar-China Border Trade Drops US$200 M Amid Coronavirus Outbreak",
                imgurl : "img/news-img/news-25220c.png",
                detailurl : "news-25220c.html",
                region: "Shan",
                date : new Date("2020-2-25"),
            },
            {
                heading : "Italy Reports 148 Deaths From Coronavirus, With Over 3,800 Infected",
                imgurl : "img/news-img/news-6320c.png",
                detailurl : "news-6320c.html",
                region: "Europe",
                date : new Date("2020-3-6"),
            },
            {
                heading : "Death Toll From Coronavirus in Italy Tops 1,000",
                imgurl : "img/news-img/news-13320a.png",
                detailurl : "news-13320a.html",
                region: "Europe",
                date : new Date("2020-3-13"),
            },
             {
                heading : "Italy Reports Over 30,000 Coronavirus Cases With More Than 2,500 Deaths",
                imgurl : "img/news-img/news-18320b.png",
                detailurl : "news-18320b.html",
                region: "Europe",
                date : new Date("2020-3-18"),
            },
            {
                heading : "H&M Lines Up Supply Chain to Deliver Protective Gear to Hospitals",
                imgurl : "img/news-img/news-23320a.png",
                detailurl : "news-23320a.html",
                region: "Europe",
                date : new Date("2020-3-23"),
            },
            {
                heading : "China Virus Death Toll Passes 100 as US, Canada Issue Travel Warnings",
                imgurl : "img/news-img/news-28120b.png",
                detailurl : "news-28120b.html",
                region: "North America",
                date : new Date("2020-1-28"),
            },
            {
                heading : "US Evacuees From Virus-Hit Wuhan Quarantined at California Air Base",
                imgurl : "img/news-img/news-30120a.png",
                detailurl : "news-30120a.html",
                region: "North America",
                date : new Date("2020-1-30"),
            },
            {
                heading : "California Declares Emergency Over Coronavirus as Death Toll Rises in US",
                imgurl : "img/news-img/news-5320a.png",
                detailurl : "news-5320a.html",
                region: "North America",
                date : new Date("2020-3-5"),
            },
            {
                heading : "US Extends Stay-at-Home Guidelines to End of April to Fight Virus",
                imgurl : "img/news-img/news-30320c.png",
                detailurl : "news-30320c.html",
                region: "North America",
                date : new Date("2020-3-30"),
            },
            {
                heading : "Latest COVID-19 Developments in Myanmar: April 1, 2020",
                imgurl : "img/news-img/news-1420a.png",
                detailurl : "news-1420a.html",
                region: "Yangon",
                date : new Date("2020-4-1"),
            },
            {
                heading : "Ambassadors Call for End to Conflict in Myanmar Amid COVID-19",
                imgurl : "img/news-img/news-2420e.png",
                detailurl : "news-2420e.html",
                region: "Yangon",
                date : new Date("2020-4-2"),
            },
            {
                heading : "China Must Compensate World for COVID-19: Myanmar's Cardinal",
                imgurl : "img/news-img/news-3420e.png",
                detailurl : "news-3420e.html",
                region: "Yangon",
                date : new Date("2020-4-3"),
            },
            {
                heading : "'All Myanmar Is a Horror'—Facebook Mistranslates Daw Aung San Suu Kyi's Post",
                imgurl : "img/news-img/news-3420f.png",
                detailurl : "news-3420f.html",
                region: "Yangon",
                date : new Date("2020-4-3"),
            },
            {
                heading : "Myanmar Has Run Over 1,000 COVID-19 Tests; 20 Turned Out Positive",
                imgurl : "img/news-img/news-3420h.png",
                detailurl : "news-3420h.html",
                region: "Yangon",
                date : new Date("2020-4-3"),
            },
            {
                heading : "Myanmar Health Workers Sing to Lift Spirits of People in Quarantine",
                imgurl : "img/news-img/news-3420i.png",
                detailurl : "news-3420i.html",
                region: "Yangon",
                date : new Date("2020-4-3"),
            },
            {
                heading : "Myanmar's State Counselor Vows 'Zero Tolerance' for Price Gougers of COVID-19 Protective Items",
                imgurl : "img/news-img/news-6420d.png",
                detailurl : "news-6420d.html",
                region: "Yangon",
                date : new Date("2020-4-6"),
            },
            {
                heading : "Myanmar Pharma Firm Donates Device to Massively Increase COVID-19 Testing",
                imgurl : "img/news-img/news-6420e.png",
                detailurl : "news-6420e.html",
                region: "Yangon",
                date : new Date("2020-4-6"),
            },
            {
                heading : "Myanmar's KBZ Bank Donates Nearly $1M to Coronavirus Efforts",
                imgurl : "img/news-img/news-6420f.png",
                detailurl : "news-6420f.html",
                region: "Yangon",
                date : new Date("2020-4-6"),
            },
            {
                heading : "Myanmar Government Bans Staff From New Year Travel to Stop COVID-19 Spread",
                imgurl : "img/news-img/news-6420i.png",
                detailurl : "news-6420i.html",
                region: "Yangon",
                date : new Date("2020-4-6"),
            },
            {
                heading : "Myanmar Govt to Provide Free Basic Food for Poor During COVID-19 Shutdown",
                imgurl : "img/news-img/news-6420n.png",
                detailurl : "news-6420n.html",
                region: "Yangon",
                date : new Date("2020-4-6"),
            },
            {
                heading : "Myanmar Reports 22nd COVID-19 Case",
                imgurl : "img/news-img/news-7420a.png",
                detailurl : "news-7420a.html",
                region: "Yangon",
                date : new Date("2020-4-7"),
            },
            {
                heading : "Myanmar Public Overwhelmingly Backs Crackdown on Wildlife Markets to Prevent Pandemics: Survey",
                imgurl : "img/news-img/news-7420b.png",
                detailurl : "news-7420b.html",
                region: "Yangon",
                date : new Date("2020-4-7"),
            },
            {
                heading : "Myanmar Firms to Make Face Masks to Meet COVID-19 Demand",
                imgurl : "img/news-img/news-7420c.png",
                detailurl : "news-7420c.html",
                region: "Yangon",
                date : new Date("2020-4-7"),
            },
            {
                heading : "Myanmar Military Doctors to Staff New Makeshift COVID-19 Hospital in Yangon",
                imgurl : "img/news-img/news-7420d.png",
                detailurl : "news-7420d.html",
                region: "Yangon",
                date : new Date("2020-4-7"),
            },
            {
                heading : "Myanmar Scraps Restrictions on Movement in Two Regions",
                imgurl : "img/news-img/news-8420c.png",
                detailurl : "news-8420c.html",
                region: "Yangon",
                date : new Date("2020-4-8"),
            },
            {
                heading : "Chinese COVID-19 Specialists Arrive in Yangon",
                imgurl : "img/news-img/news-8420d.png",
                detailurl : "news-8420d.html",
                region: "Yangon",
                date : new Date("2020-4-8"),
            },
            {
                heading : "Myanmar State Counselor Says State Will Care for Family of Deceased COVID-19 Patient",
                imgurl : "img/news-img/news-8420e.png",
                detailurl : "news-8420e.html",
                region: "Yangon",
                date : new Date("2020-4-8"),
            },
            {
                heading : "Myanmar Citizens Give Up Power Subsidy to Aid COVID-19 Fight",
                imgurl : "img/news-img/news-8420i.png",
                detailurl : "news-8420i.html",
                region: "Yangon",
                date : new Date("2020-4-8"),
            },
            {
                heading : "EU Pledges Support for Women Garment Factory Workers in Myanmar",
                imgurl : "img/news-img/news-9420d.png",
                detailurl : "news-9420d.html",
                region: "Yangon",
                date : new Date("2020-4-9"),
            },
            {
                heading : "Myanmar Reports 10 New COVID-19 Cases; Total Rises to 38",
                imgurl : "img/news-img/news-12420a.png",
                detailurl : "news-12420a.html",
                region: "Yangon",
                date : new Date("2020-4-12"),
            },
            {
                heading : "Doctor Who Treated COVID-19 Patient Tests Positive in Myanmar",
                imgurl : "img/news-img/news-12420b.png",
                detailurl : "news-12420b.html",
                region: "Yangon",
                date : new Date("2020-4-12"),
            },
            {
                heading : "Myanmar Pastors Face Prosecution for Defying Ban on Religious Gatherings Amid COVID-19",
                imgurl : "img/news-img/news-14420a.png",
                detailurl : "news-14420a.html",
                region: "Yangon",
                date : new Date("2020-4-14"),
            },
            {
                heading : "Myanmar COVID-19 Death Toll Rises to Five; Curfew Imposed in Yangon",
                imgurl : "img/news-img/news-18420a.png",
                detailurl : "news-18420a.html",
                region: "Yangon",
                date : new Date("2020-4-18"),
            },
            {
                heading : "Myanmar COVID-19 Cases Reach 111, Most Traced to Pastor-led Gatherings",
                imgurl : "img/news-img/news-20420c.png",
                detailurl : "news-20420c.html",
                region: "Yangon",
                date : new Date("2020-4-20"),
            },
            {
                heading : "Military, Govt and Private Medics Staff Makeshift COVID-19 Hospital in Myanmar",
                imgurl : "img/news-img/news-20420g.png",
                detailurl : "news-20420g.html",
                region: "Yangon",
                date : new Date("2020-4-20"),
            },
            {
                heading : "Myanmar Says Factories Must Take COVID-19 Precautions Before They Reopen",
                imgurl : "img/news-img/news-20420h.png",
                detailurl : "news-20420h.html",
                region: "Yangon",
                date : new Date("2020-4-20"),
            },
            {
                heading : "Myanmar Workforce Promised Govt Payments During COVID-19 Factory Closures",
                imgurl : "img/news-img/news-21420d.png",
                detailurl : "news-21420d.html",
                region: "Yangon",
                date : new Date("2020-3-21"),
            },
             {
                heading : "World Bank Loans Myanmar $50M for COVID-19 Response",
                imgurl : "img/news-img/news-21420e.png",
                detailurl : "news-21420e.html",
                region: "Yangon",
                date : new Date("2020-3-21"),
            },
             {
                heading : "Myanmar President Orders State, Regional Govts to Battle Hate Speech Amid COVID-19 Fight",
                imgurl : "img/news-img/news-21420f.png",
                detailurl : "news-21420f.html",
                region: "Yangon",
                date : new Date("2020-3-21"),
            },
            {
                heading : "Myanmar Factories Ignoring COVID-19 Rules Face Prosecution: Suu Kyi",
                imgurl : "img/news-img/news-22420f.png",
                detailurl : "news-22420f.html",
                region: "Yangon",
                date : new Date("2020-4-22"),
            },
            {
                heading : "Myanmar Volunteers Help Yangon's Hungry During COVID-19 Outbreak",
                imgurl : "img/news-img/news-23420d.png",
                detailurl : "news-23420d.html",
                region: "Yangon",
                date : new Date("2020-4-23"),
            },
            {
                heading : "Myanmar Confirms 12 New COVID-19 Cases for Total of 139",
                imgurl : "img/news-img/news-24420c.png",
                detailurl : "news-24420c.html",
                region: "Yangon",
                date : new Date("2020-4-24"),
            },
            {
                heading : "In Myanmar, Concerns That China's Help on COVID-19 Comes With Strings Attached",
                imgurl : "img/news-img/news-24420d.png",
                detailurl : "news-24420d.html",
                region: "Yangon",
                date : new Date("2020-4-24"),
            },
            {
                heading : "Volunteers, Govt Staff Fighting COVID-19 in Myanmar Face Discrimination",
                imgurl : "img/news-img/news-2420b.png",
                detailurl : "news-2420b.html",
                region: "Mandalay",
                date : new Date("2020-4-2"),
            },
            {
                heading : "Myanmar's Military Opens COVID-19 Quarantine Center in Naypyitaw",
                imgurl : "img/news-img/news-2420c.png",
                detailurl : "news-2420c.html",
                region: "Mandalay",
                date : new Date("2020-4-2"),
            },
            {
                heading : "Mandalay Bus Company Banned for Violating Govt COVID-19 Order",
                imgurl : "img/news-img/news-3420g.png",
                detailurl : "news-3420g.html",
                region: "Mandalay",
                date : new Date("2020-4-3"),
            },
            {
            	heading : "Myanmar Confronts COVID-19",
                imgurl : "img/news-img/news-3420l.png",
                detailurl : "news-3420l.html",
                region: "Mandalay",
                date : new Date("2020-4-3"),
            },
            {
                heading : "Myanmar's Mandalay Promises Food Supplies for the Poor",
                imgurl : "img/news-img/news-6420l.png",
                detailurl : "news-6420l.html",
                region: "Mandalay",
                date : new Date("2020-4-6"),
            },
            {
                heading : "Myanmar's Military Donates Wages to COVID-19 Fight",
                imgurl : "img/news-img/news-7420f.png",
                detailurl : "news-7420f.html",
                region: "Mandalay",
                date : new Date("2020-4-7"),
            },
            {
                heading : "Myanmar's Education Ministry Closes Offices Amid COVID-19 Scare",
                imgurl : "img/news-img/news-8420g.png",
                detailurl : "news-8420g.html",
                region: "Mandalay",
                date : new Date("2020-4-8"),
            },
            {
                heading : "Latest COVID-19 Developments in Myanmar: April 9, 2020",
                imgurl : "img/news-img/news-9420c.png",
                detailurl : "news-9420c.html",
                region: "Mandalay",
                date : new Date("2020-4-9"),
            },
            {
                heading : "Two Children Among Latest COVID-19 Cases in Myanmar",
                imgurl : "img/news-img/news-3420c.png",
                detailurl : "news-3420c.html",
                region: "Bago",
                date : new Date("2020-4-3"),
            },
            {
                heading : "COVID-19 Patient's Dog Spared From Execution in Myanmar  ",
                imgurl : "img/news-img/news-3420k.png",
                detailurl : "news-3420k.html",
                region: "Bago",
                date : new Date("2020-4-3"),
            },
            {
                heading : "Man Killed in Sword Attack After COVID-19 Argument in Myanmar's Bago Region",
                imgurl : "img/news-img/news-6420j.png",
                detailurl : "news-6420j.html",
                region: "Bago",
                date : new Date("2020-4-6"),
            },
            {
                heading : "Myanmar Reports Two More COVID-19 Deaths, Taking Toll to Three",
                imgurl : "img/news-img/news-8420b.png",
                detailurl : "news-8420b.html",
                region: "Bago",
                date : new Date("2020-4-6"),
            },
            {
                heading : "Myanmar Govt Cracks Down on Fake COVID-19 News",
                imgurl : "img/news-img/news-6420h.png",
                detailurl : "news-6420h.html",
                region: "Sagaing",
                date : new Date("2020-4-6"),
            },
            {
                heading : "Myanmar Citizens Face COVID-19 Prosecutions for Breaching Rules",
                imgurl : "img/news-img/news-10420a.png",
                detailurl : "news-10420a.html",
                region: "Ayeyarwady",
                date : new Date("2020-4-10"),
            },
             {
                heading : "Factories in Myanmar's Ayeyarwady Region to Close Ahead of COVID-19 Checks",
                imgurl : "img/news-img/news-22420d.png",
                detailurl : "news-22420d.html",
                region: "Ayeyarwady",
                date : new Date("2020-4-22"),
            },
            {
                heading : "Courts Send COVID-19 Curfew Breakers to Prison in Myanmar",
                imgurl : "img/news-img/news-23420e.png",
                detailurl : "news-23420e.html",
                region: "Ayeyarwady",
                date : new Date("2020-4-23"),
            },
            {
                heading : "Myanmar's Yangon, Ayeyarwady Regions Extend COVID-19 Curfews for 2 Months",
                imgurl : "img/news-img/news-24420f.png",
                detailurl : "news-24420f.html",
                region: "Ayeyarwady",
                date : new Date("2020-4-24"),
            },
            {
                heading : "Thousands of Myanmar Migrant Workers Return from China into Quarantine",
                imgurl : "img/news-img/news-20420e.png",
                detailurl : "news-20420e.html",
                region: "Kachin",
                date : new Date("2020-4-20"),
            },
            {
                heading : "Myanmar Migrant Workers Face 14-Day Quarantine on Thai Border",
                imgurl : "img/news-img/news-8420h.png",
                detailurl : "news-8420h.html",
                region: "Kayin",
                date : new Date("2020-4-8"),
            },
            {
                heading : "Myanmar's Chin State Extends COVID-19 Village Lockdown",
                imgurl : "img/news-img/news-23420f.png",
                detailurl : "news-23420f.html",
                region: "Chin",
                date : new Date("2020-4-23"),
            },
            {
                heading : "Myanmar's  Mon State Consolidates Quarantine Centers for Returning Migrants",
                imgurl : "img/news-img/news-6420k.png",
                detailurl : "news-6420k.html",
                region: "Mon",
                date : new Date("2020-4-6"),
            },
            {
                heading : "WHO Driver Transporting COVID-19 Swabs Killed as Vehicle Attacked in Western Myanmar",
                imgurl : "img/news-img/news-21420c.png",
                detailurl : "news-21420c.html",
                region: "Rakhine",
                date : new Date("2020-4-21"),
            },
            {
                heading : "Myanmar Vows to Probe Killing of WHO Driver Transporting COVID-19 Swabs",
                imgurl : "img/news-img/news-22420b.png",
                detailurl : "news-22420b.html",
                region: "Rakhine",
                date : new Date("2020-4-22"),
            },
            {
                heading : "COVID-19 Swabs to be Flown from Myanmar's Rakhine After Fatal Shooting",
                imgurl : "img/news-img/news-22420e.png",
                detailurl : "news-22420e.html",
                region: "Rakhine",
                date : new Date("2020-4-22"),
            },
            {
                heading : "Western Myanmar's Remote Naga Area Braces for COVID-19",
                imgurl : "img/news-img/news-3420d.png",
                detailurl : "news-3420d.html",
                region: "Shan",
                date : new Date("2020-4-3"),
            },
            {
                heading : "In Myanmar, It's'Time to Stop the Senseless War and Fight COVID-19",
                imgurl : "img/news-img/news-11420a.png",
                detailurl : "news-11420a.html",
                region: "Shan",
                date : new Date("2020-4-11"),
            },
            {
                heading : "Myanmar's Shan State Imposes COVID-19 Curfew",
                imgurl : "img/news-img/news-20420f.png",
                detailurl : "news-20420f.html",
                region: "Shan",
                date : new Date("2020-4-20"),
            },
            {
                heading : "Shan State Ministers, Over 30 State Employees in Quarantine for COVID-19",
                imgurl : "img/news-img/news-22420a.png",
                detailurl : "news-22420a.html",
                region: "Shan",
                date : new Date("2020-4-22"),
            },
            {
                heading : "Over 200 People Exposed to COVID-19 Patient in Myanmar's Shan State",
                imgurl : "img/news-img/news-22420c.png",
                detailurl : "news-22420c.html",
                region: "Shan",
                date : new Date("2020-4-22"),
            },
            {
                heading : "China Closes Myanmar Border to Stop COVID-19 Returning",
                imgurl : "img/news-img/news-24420e.png",
                detailurl : "news-24420e.html",
                region: "Shan",
                date : new Date("2020-4-24"),
            },
            {
                heading : "Mass Disinfections to Combat Coronavirus Pose New Health Hazard",
                imgurl : "img/news-img/news-1420c.png",
                detailurl : "news-1420c.html",
                region: "Asia",
                date : new Date("2020-4-1"),
            },
            {
                heading : "Bangkok to Close Parks as Thailand's Coronavirus Cases Rise",
                imgurl : "img/news-img/news-2420a.png",
                detailurl : "news-2420a.html",
                region: "Asia",
                date : new Date("2020-4-2"),
            },
            {
                heading : "Singapore Sees Record Rise in COVID-19 Cases, Quarantines 20,000 Migrant Workers",
                imgurl : "img/news-img/news-6420a.png",
                detailurl : "news-6420a.html",
                region: "Asia",
                date : new Date("2020-4-6"),
            },
            {
                heading : "China Reports 30 New Coronavirus Cases, Three Deaths",
                imgurl : "img/news-img/news-6420g.png",
                detailurl : "news-6420g.html",
                region: "Asia",
                date : new Date("2020-4-6"),
            },
            {
                heading : "Major Japanese Cities Go Quiet as State of Emergency Declared",
                imgurl : "img/news-img/news-8420a.png",
                detailurl : "news-8420a.html",
                region: "Asia",
                date : new Date("2020-4-8"),
            },
            {
                heading : "Coronavirus Having Serious Impact on Japanese Economy: BOJ Chief",
                imgurl : "img/news-img/news-9420a.png",
                detailurl : "news-9420a.html",
                region: "Asia",
                date : new Date("2020-4-9"),
            },
            {
                heading : "WHO Chief Appears to Take Dig at Trump's Threat to Freeze Funding",
                imgurl : "img/news-img/news-9420b.png",
                detailurl : "news-9420b.html",
                region: "Asia",
                date : new Date("2020-4-9"),
            },
            {
                heading : "South Korea Relaxes Some Social Distancing Rules as New Virus Cases Fall",
                imgurl : "img/news-img/news-20420a.png",
                detailurl : "news-20420a.html",
                region: "Asia",
                date : new Date("2020-4-20"),
            },
            {
                heading : "China Reports 16 More Coronavirus Cases, More Than Half Imported",
                imgurl : "img/news-img/news-20420d.png",
                detailurl : "news-20420d.html",
                region: "Asia",
                date : new Date("2020-4-20"),
            },
            {
                heading : "Taiwan Sees Spike in COVID-19 Cases Due to Navy Outbreak",
                imgurl : "img/news-img/news-20420i.png",
                detailurl : "news-20420i.html",
                region: "Asia",
                date : new Date("2020-4-20"),
            },
            {
                heading : "Singapore Extends Partial Lockdown Until June 1 as Infections Surge",
                imgurl : "img/news-img/news-22420g.png",
                detailurl : "news-22420g.html",
                region: "Asia",
                date : new Date("2020-4-22"),
            },
            {
                heading : "China Reports 72 New COVID-19 Cases; Flare-Up Continues in North",
                imgurl : "img/news-img/news-22420h.png",
                detailurl : "news-22420h.html",
                region: "Asia",
                date : new Date("2020-4-22"),
            },
            {
                heading : "India Restarts Factories, Farming in Rural Areas Even as Coronavirus Cases Rise",
                imgurl : "img/news-img/news-21420a.png",
                detailurl : "news-21420a.html",
                region: "Asia",
                date : new Date("2020-4-21"),
            },
            {
                heading : "Vietnam to Ease Nationwide Coronavirus Lockdown",
                imgurl : "img/news-img/news-23420a.png",
                detailurl : "news-23420a.html",
                region: "Asia",
                date : new Date("2020-4-23"),
            },
            {
                heading : "India Suspends Coronavirus Antibody Tests Amid Questions Over Reliability",
                imgurl : "img/news-img/news-23420b.png",
                detailurl : "news-23420b.html",
                region: "Asia",
                date : new Date("2020-4-23"),
            },
            {
                heading : "Philippines Extends Capital's Coronavirus Lockdown to May 15",
                imgurl : "img/news-img/news-24420a.png",
                detailurl : "news-24420a.html",
                region: "Asia",
                date : new Date("2020-4-24"),
            },
            {
                heading : "South Africa coronavirus: Record one-day test, prez mocks 'mask mishap'",
                imgurl : "img/news-img/news-24420g.jpg",
                detailurl : "news-24420g.html",
                region: "Africa",
                date : new Date("2020-4-24"),
            },
            {
                heading : "Ghana coronavirus: case count hits 1,279; two new regions 'infected'",
                imgurl : "img/news-img/news-24420h.jpg",
                detailurl : "news-24420h.html",
                region: "Africa",
                date : new Date("2020-4-24"),
            },
            {
                heading : "Ethiopia coronavirus cases at 117, Tigray relaxes state of emergency",
                imgurl : "img/news-img/news-24420i.jpg",
                detailurl : "news-24420i.html",
                region: "Africa",
                date : new Date("2020-4-24"),
            },
            {
                heading : "Cameroon coronavirus: boom in recoveries amid official tally controversies",
                imgurl : "img/news-img/news-24420j.jpg",
                detailurl : "news-24420j.html",
                region: "Africa",
                date : new Date("2020-4-24"),
            },
            {
                heading : "Cameroon coronavirus: boom in recoveries amid official tally controversies",
                imgurl : "img/news-img/news-24420k.jpg",
                detailurl : "news-24420k.html",
                region: "Africa",
                date : new Date("2020-4-24"),
            },
            {
                heading : "Coronavirus in Africa: 27,385 cases; 1,297 deaths; 8,172 recoveries",
                imgurl : "img/news-img/news-24420l.jpg",
                detailurl : "news-24420l.html",
                region: "Africa",
                date : new Date("2020-4-24"),
            },
            {
                heading : "Botswana coronavirus: quarantined prez, MPs released after testing negative",
                imgurl : "img/news-img/news-23420g.jpg",
                detailurl : "news-23420g.html",
                region: "Africa",
                date : new Date("2020-4-23"),
            },
            {
                heading : "Botswana coronavirus: quarantined prez, MPs released after testing negative",
                imgurl : "img/news-img/news-23420h.jpg",
                detailurl : "news-23420h.html",
                region: "Africa",
                date : new Date("2020-4-23"),
            },
            {
                heading : "Coronavirus: Africa's most impacted, cases near 26,000, SA hits 1,000 recoveries",
                imgurl : "img/news-img/news-23420i.jpg",
                detailurl : "news-23420i.html",
                region: "Africa",
                date : new Date("2020-4-23"),
            },
            {
                heading : "ECOWAS leaders meet - online - to discuss impact of COVID-19",
                imgurl : "img/news-img/news-23420j.jpg",
                detailurl : "news-23420j.html",
                region: "Africa",
                date : new Date("2020-4-23"),
            },
            {
                heading : "Muslims start Ramadan fasting on April 24 amid pandemic",
                imgurl : "img/news-img/news-23420k.jpg",
                detailurl : "news-23420k.html",
                region: "Africa",
                date : new Date("2020-4-23"),
            },
            {
                heading : "Sierra Leone coronavirus: president quarantines after guard tests positive",
                imgurl : "img/news-img/news-21420g.jpg",
                detailurl : "news-21420g.html",
                region: "Africa",
                date : new Date("2020-4-21"),
            },
            {
                heading : "Africa's top coronavirus deaths: Guinea president's right-hand man succumbs",
                imgurl : "img/news-img/news-20420j.jpg",
                detailurl : "news-20420j.html",
                region: "Africa",
                date : new Date("2020-4-20"),
            },
            {
                heading : "Coronavirus: 19 poor African countries benefit from IMF debt service relief",
                imgurl : "img/news-img/news-14420b.jpg",
                detailurl : "news-14420b.html",
                region: "Africa",
                date : new Date("2020-4-14"),
            },
            {
                heading : "Coronavirus: Buhari meets VP, Task Force; speaker warns Chinese envoy",
                imgurl : "img/news-img/news-12420c.jpg",
                detailurl : "news-12420c.html",
                region: "Africa",
                date : new Date("2020-4-12"),
            },
            {
                heading : "Grounded! COVID-19 pulls brakes on Africa's 'frequent-flier' presidents",
                imgurl : "img/news-img/news-7420g.jpg",
                detailurl : "news-7420g.html",
                region: "Africa",
                date : new Date("2020-4-7"),
            },
            {
                heading : "Coronavirus patients on chloroquine heal faster - Senegalese medic",
                imgurl : "img/news-img/news-6420o.jpg",
                detailurl : "news-6420o.html",
                region: "Africa",
                date : new Date("2020-4-6"),
            },
            {
                heading : "Senegal extends state of emergency for coronavirus",
                imgurl : "img/news-img/news-5420a.jpg",
                detailurl : "news-5420a.html",
                region: "Africa",
                date : new Date("2020-4-5"),
            },
            {
                heading : "Nigeria's Osun state says only one coronavirus patient 'missing'",
                imgurl : "img/news-img/news-4420a.jpg",
                detailurl : "news-4420a.html",
                region: "Africa",
                date : new Date("2020-4-4"),
            },
            {
                heading : "Coronavirus: Zimbabwe beer ban U-turn, AU leaders meet, Cameroon tally booms",
                imgurl : "img/news-img/news-4420b.jpg",
                detailurl : "news-4420b.html",
                region: "Africa",
                date : new Date("2020-4-4"),
            },
            {
                heading : "Notice to African presidents, COVID-19 will shrink your security forces ǀ View",
                imgurl : "img/news-img/news-4420c.jpg",
                detailurl : "news-4420c.html",
                region: "Africa",
                date : new Date("2020-4-4"),
            },
            {
                heading : "Niger president agrees with Talon: lockdowns are not Africa-friendly",
                imgurl : "img/news-img/news-3420m.jpg",
                detailurl : "news-3420m.html",
                region: "Africa",
                date : new Date("2020-4-3"),
            },
            {
                heading : "Kenya president apologizes for police excesses during curfew",
                imgurl : "img/news-img/news-3420n.jpg",
                detailurl : "news-3420n.html",
                region: "Africa",
                date : new Date("2020-4-3"),
            },
            {
                heading : "'Close up' social distancing as Lagos distributes coronavirus food aid",
                imgurl : "img/news-img/news-3420o.jpg",
                detailurl : "news-3420o.html",
                region: "Africa",
                date : new Date("2020-4-3"),
            },
            {
                heading : "Africa needs $100 bn economic stimulus amid coronavirus combat - UNECA",
                imgurl : "img/news-img/news-1420d.jpg",
                detailurl : "news-1420d.html",
                region: "Africa",
                date : new Date("2020-4-1"),
            },
            {
                heading : "Coronavirus Death Toll Tops 41,000 Worldwide, With 850,000 Infections",
                imgurl : "img/news-img/news-1420b.png",
                detailurl : "news-1420b.html",
                region: "Europe",
                date : new Date("2020-4-1"),
            },
            {
                heading : "Britons Reconvene on Doorsteps to Clap for Health Workers",
                imgurl : "img/news-img/news-3420a.png",
                detailurl : "news-3420a.html",
                region: "Europe",
                date : new Date("2020-4-3"),
            },
            {
                heading : "British PM Boris Johnson Admitted to Hospital as COVID-19 Symptoms Persist",
                imgurl : "img/news-img/news-6420b.png",
                detailurl : "news-6420b.html",
                region: "Europe",
                date : new Date("2020-4-6"),
            },
            {
                heading : "Coronavirus: Czechs free to move again",
                imgurl : "img/news-img/news-24420n.jpg",
                detailurl : "news-24420n.html",
                region: "Europe",
                date : new Date("2020-4-24"),
            },
            {
                heading : "Coronavirus: Czechs free to move again",
                imgurl : "img/news-img/news-23420n.jpg",
                detailurl : "news-23420n.html",
                region: "Europe",
                date : new Date("2020-4-23"),
            },
            {
                heading : "US announces millions in aid for resource-rich Greenland",
                imgurl : "img/news-img/news-23420o.jpg",
                detailurl : "news-23420o.html",
                region: "Europe",
                date : new Date("2020-4-23"),
            },
            {
                heading : "Coronavirus: Newcastle University tracking virus in sewage",
                imgurl : "img/news-img/news-23420p.jpg",
                detailurl : "news-23420p.html",
                region: "Europe",
                date : new Date("2020-4-23"),
            },
            {
                heading : "Coronavirus: Germany's states make face masks compulsory",
                imgurl : "img/news-img/news-22420i.jpg",
                detailurl : "news-22420i.html",
                region: "Europe",
                date : new Date("2020-4-22"),
            },
            {
                heading : "Coronavirus: Spanish PM Sánchez sees 'slow and gradual' end to lockdown",
                imgurl : "img/news-img/news-22420j.jpg",
                detailurl : "news22420j.html",
                region: "Europe",
                date : new Date("2020-4-22"),
            },
            {
                heading : "Coronavirus: Romania hands out steep lockdown fines",
                imgurl : "img/news-img/news-22420k.jpg",
                detailurl : "news-22420k.html",
                region: "Europe",
                date : new Date("2020-4-22"),
            },
            {
                heading : "Eredivisie: Dutch top flight likely to be cancelled after major events ban extended",
                imgurl : "img/news-img/news-21420j.jpg",
                detailurl : "news-21420j.html",
                region: "Europe",
                date : new Date("2020-4-21"),
            },
            {
                heading : "Coronavirus: Ireland bans major mass gatherings until autumn",
                imgurl : "img/news-img/news-21420k.jpg",
                detailurl : "news-21420k.html",
                region: "Europe",
                date : new Date("2020-4-21"),
            },
            {
                heading : "Coronavirus: Republic of Ireland's death toll rises by 77",
                imgurl : "img/news-img/news-20420l.jpg",
                detailurl : "news-20420l.html",
                region: "Europe",
                date : new Date("2020-4-20"),
            },
            {
                heading : "Coronavirus: Germany relaxes shop closures",
                imgurl : "img/news-img/news-20420m.jpg",
                detailurl : "news-20420m.html",
                region: "Europe",
                date : new Date("2020-4-20"),
            },
            {
                heading : "Coronavirus: Spanish PM promises to ease confinement of children",
                imgurl : "img/news-img/news-19420b.jpg",
                detailurl : "news-19420b.html",
                region: "Europe",
                date : new Date("2020-4-19"),
            },
            {
                heading : "Coronavirus: Number of deaths rises to 530 in Ireland",
                imgurl : "img/news-img/news-17420a.jpg",
                detailurl : "news-17420a.html",
                region: "Europe",
                date : new Date("2020-4-17"),
            },
            {
                heading : "Coronavirus: Germany says its outbreak is 'under control'",
                imgurl : "img/news-img/news-17420b.jpg",
                detailurl : "news-17420b.html",
                region: "Europe",
                date : new Date("2020-4-17"),
            },{
                heading : "Coronavirus: 668 infected on French aircraft carrier Charles de Gaulle",
                imgurl : "img/news-img/news-16420d.jpg",
                detailurl : "news-16420d.html",
                region: "Europe",
                date : new Date("2020-4-16"),
            },
            {
                heading : "Coronavirus: EU offers 'heartfelt apology' to Italy",
                imgurl : "img/news-img/news-16420e.jpg",
                detailurl : "news-16420e.html",
                region: "Europe",
                date : new Date("2020-4-16"),
            },
            {
                heading : "Coronavirus: Germany slowly eases lockdown measures",
                imgurl : "img/news-img/news-15420c.jpg",
                detailurl : "news-15420c.html",
                region: "Europe",
                date : new Date("2020-4-15"),
            },
            {
                heading : "Coronavirus: Denmark lets young children return to school",
                imgurl : "img/news-img/news-15420d.jpg",
                detailurl : "news-15420d.html",
                region: "Europe",
                date : new Date("2020-4-15"),
            },
            {
                heading : "Coronavirus: 41 more deaths in Ireland bring total to 406",
                imgurl : "img/news-img/news-14420c.jpg",
                detailurl : "news-14420c.html",
                region: "Europe",
                date : new Date("2020-4-14"),
            },
            {
                heading : "Italian Football Federation hopes to test players for coronavirus in May before season restart",
                imgurl : "img/news-img/news-13420a.jpg",
                detailurl : "news-13420a.html",
                region: "Europe",
                date : new Date("2020-4-13"),
            },
            {
                heading : "Coronavirus: 'Deadly resurgence' if curbs lifted too early, WHO warns",
                imgurl : "img/news-img/news-10420b.jpg",
                detailurl : "news-10420b.html",
                region: "Europe",
                date : new Date("2020-4-10"),
            },
            {
                heading : "Coronavirus: Irish restrictions extended until 5 May",
                imgurl : "img/news-img/news-10420c.jpg",
                detailurl : "news-10420c.html",
                region: "Europe",
                date : new Date("2020-4-10"),
            },
            {
                heading : "Coronavirus Infections Top 1 Million Worldwide",
                imgurl : "img/news-img/news-3420b.png",
                detailurl : "news-3420b.html",
                region: "North America",
                date : new Date("2020-4-3"),
            },
            {
                heading : "Coronavirus Infections Top 1 Million Worldwide",
                imgurl : "img/news-img/news-6420c.png",
                detailurl : "news-6420c.html",
                region: "North America",
                date : new Date("2020-4-6"),
            },
            {
                heading : "Who's Who of Pop Culture Unites for 'One World' Coronavirus Special",
                imgurl : "img/news-img/news-20420b.png",
                detailurl : "news-20420b.html",
                region: "North America",
                date : new Date("2020-4-20"),
            },
            {
                heading : "China May Be Keeping COVID-19 Data for Commercial Gain: Trump Adviser",
                imgurl : "img/news-img/news-21420b.png",
                detailurl : "news-21420b.html",
                region: "North America",
                date : new Date("2020-4-213420b"),
            },
            {
                heading : "Two New York Cats Become First US Pets to Test Positive for COVID-19",
                imgurl : "img/news-img/news-23420c.png",
                detailurl : "news-23420c.html",
                region: "North America",
                date : new Date("2020-4-23"),
            },
            {
                heading : "Trump Downplays Concerns Over Return of Coronavirus Later This Year",
                imgurl : "img/news-img/news-24420b.png",
                detailurl : "news-24420b.html",
                region: "North America",
                date : new Date("2020-4-24"),
            },
            {
                heading : "Coronavirus: President Trump defends tweets against US states' lockdowns",
                imgurl : "img/news-img/news-18420b.jpg",
                detailurl : "news-18420b.html",
                region: "North America",
                date : new Date("2020-4-18"),
            },
            {
                heading : "Coronavirus: Trump unveils plan to reopen states in phases",
                imgurl : "img/news-img/news-17420c.jpg",
                detailurl : "news-17420c.html",
                region: "North America",
                date : new Date("2020-4-17"),
            },
            {
                heading : "Coronavirus: Is President Trump right to criticise the WHO?",
                imgurl : "img/news-img/news-15420e.jpg",
                detailurl : "news-15420e.html",
                region: "North America",
                date : new Date("2020-4-15"),
            },
            {
                heading : "Canadian care homes become coronavirus hotspots",
                imgurl : "img/news-img/news-13420b.jpg",
                detailurl : "news-13420b.html",
                region: "North America",
                date : new Date("2020-4-13"),
            },
            {
                heading : "More US states begin lifting virus lockdown orders",
                imgurl : "img/news-img/news-27420a.jpg",
                detailurl : "news-27420a.html",
                region: "North America",
                date : new Date("2020-4-27"),
            },
            {
                heading : "Coronavirus: New York to allow tests in pharmacies",
                imgurl : "img/news-img/news-26420a.jpg",
                detailurl : "news-26420a.html",
                region: "North America",
                date : new Date("2020-4-26"),
            },
            {
                heading : "Coronavirus: US and China trade conspiracy theories",
                imgurl : "img/news-img/news-26420b.jpg",
                detailurl : "news-26420b.html",
                region: "North America",
                date : new Date("2020-4-26"),
            },
            {
                heading : "Coronavirus: Some states begin to reopen as US death toll passes 50,000",
                imgurl : "img/news-img/news-25420a.png",
                detailurl : "news-25420a.html",
                region: "North America",
                date : new Date("2020-4-25"),
            },
            {
                heading : "Coronavirus: US death toll passes 50,000 in world's deadliest outbreak",
                imgurl : "img/news-img/news-24420o.jpg",
                detailurl : "news-24420o.html",
                region: "North America",
                date : new Date("2020-4-24"),
            },
            {
                heading : "Coronavirus: Uruguay reopens some rural schools",
                imgurl : "img/news-img/news-23420l.jpg",
                detailurl : "news-23420l.html",
                region: "South America",
                date : new Date("2020-4-23"),
            },
            {
                heading : "Chile lockdown: Anti-government protest broken up by police",
                imgurl : "img/news-img/news-21420h.jpg",
                detailurl : "news-21420h.html",
                region: "South America",
                date : new Date("2020-4-21"),
            },
            {
                heading : "Coronavirus: Backpacker home after 35 days in Peru lockdown",
                imgurl : "img/news-img/news-21420i.jpg",
                detailurl : "news-21420i.html",
                region: "South America",
                date : new Date("2020-4-21"),
            },
            {
                heading : "Coronavirus: Brazil's Bolsonaro joins anti-lockdown protests",
                imgurl : "img/news-img/news-20420k.jpg",
                detailurl : "news-20420k.html",
                region: "South America",
                date : new Date("2020-4-20"),
            },
            {
                heading : "We are not prepared at all': Haiti, already impoverished, confronts a pandemic",
                imgurl : "img/news-img/news-19420a.jpg",
                detailurl : "news-19420a.html",
                region: "South America",
                date : new Date("2020-4-19"),
            },
            {
                heading : "Coronavirus nightmare in Ecuador's port city Guayaquil - pictures",
                imgurl : "img/news-img/news-17420g.jpg",
                detailurl : "news-17420g.html",
                region: "South America",
                date : new Date("2020-4-17"),
            },
            {
                heading : "Coronavirus: Bolsonaro fires health minister over pandemic response",
                imgurl : "img/news-img/news-16420a.jpg",
                detailurl : "news-16420a.html",
                region: "South America",
                date : new Date("2020-4-16"),
            },
            {
                heading : "Coronavirus: 'Undocumented explosion' spreads around Brazil",
                imgurl : "img/news-img/news-16420b.jpg",
                detailurl : "news-16420b.html",
                region: "South America",
                date : new Date("2020-4-16"),
            },
            {
                heading : "Coronavirus: Chilean writer Luis Sepúlveda dies aged 70",
                imgurl : "img/news-img/news-16420c.jpg",
                detailurl : "news-16420c.html",
                region: "South America",
                date : new Date("2020-4-16"),
            },
            {
                heading : "Coronavirus: Second Brazilian governor tests positive",
                imgurl : "img/news-img/news-15420a.jpg",
                detailurl : "news-15420a.html",
                region: "South America",
                date : new Date("2020-4-15"),
            },
            {
                heading : "Why coronavirus could be catastrophic for Venezuela",
                imgurl : "img/news-img/news-12420d12420d.jpg",
                detailurl : "news-12420d.html",
                region: "South America",
                date : new Date("2020-4-12"),
            },
            {
                heading : "Coronavirus: Brazil reports over 1,000 deaths",
                imgurl : "img/news-img/news-11420b.jpg",
                detailurl : "news-11420b.html",
                region: "South America",
                date : new Date("2020-4-11"),
            },
            {
                heading : "Coronavirus 'could wipe out Brazil's indigenous people'",
                imgurl : "img/news-img/news-6420p.jpg",
                detailurl : "news-6420p.html",
                region: "South America",
                date : new Date("2020-4-6"),
            },
            {
                heading : "Coronavirus: Peru limits movement by gender to stem spread",
                imgurl : "img/news-img/news-3420p.jpg",
                detailurl : "news-3420p.html",
                region: "South America",
                date : new Date("2020-4-3 "),
            },
            {
                heading : "Coronavirus: Brazil's favela residents organise to stop the spread",
                imgurl : "img/news-img/news-2420f.jpg",
                detailurl : "news-2420f.html",
                region: "South America",
                date : new Date("2020-4-2"),
            },
            {
                heading : "Tom Hanks, Wife Rita Wilson Test Positive for Coronavirus in Australia",
                imgurl : "img/news-img/news-12320c.png",
                detailurl : "news-12320c.html",
                region: "Oceania",
                date : new Date("2020-3-12"),
            },
            {
                heading : "Tom Hanks writes to boy called Corona who said he was bullied",
                imgurl : "img/news-img/news-24420m.jpg",
                detailurl : "news-24420m.html",
                region: "Oceania",
                date : new Date("2020-4-24"),
            },
            {
                heading : "Coronavirus: Australia's economy faces unprecedented setbacks",
                imgurl : "img/news-img/news-15420b.jpg",
                detailurl : "news-15420b.html",
                region: "Oceania",
                date : new Date("2020-4-14"),
            },
            {
                heading : "Coronavirus: Australia urges G20 action on wildlife wet markets",
                imgurl : "img/news-img/news-23420m.jpg",
                detailurl : "news-23420m.html",
                region: "Oceania",
                date : new Date("2020-4-23"),
            },
            {
                heading : "Surfing: Coronavirus lockdown advice leaves room for confusion",
                imgurl : "img/news-img/news-9420e.jpg",
                detailurl : "news-9420e.html",
                region: "Oceania",
                date : new Date("2020-4-9"),
            },
            {
                heading : "Coronavirus: Australia launches criminal investigation into Ruby Princess",
                imgurl : "img/news-img/news-5420b.jpg",
                detailurl : "news-5420b.html",
                region: "Oceania",
                date : new Date("2020-4-5"),
            },
            {
                heading : "Coronavirus: Artania cruise ship stand-off continues in Australia",
                imgurl : "img/news-img/news-1420e.jpg",
                detailurl : "news-1420e.html",
                region: "Oceania",
                date : new Date("2020-4-1"),
            },
            {
                heading : "Tom Hanks and Rita Wilson 'feel better' after coronavirus diagnosis",
                imgurl : "img/news-img/news-23320h.jpg",
                detailurl : "news-23320h.html",
                region: "Oceania",
                date : new Date("2020-3-23"),
            },
            {
                heading : "Coronavirus: Australia to close pubs, cafes and places of worship",
                imgurl : "img/news-img/news-22320a.jpg",
                detailurl : "news-22320a.html",
                region: "Oceania",
                date : new Date("2020-3-22"),
            },
            {
                heading : "Coronavirus: Australia bans 'non-essential' gatherings of over 100 people",
                imgurl : "img/news-img/news-18320f.jpg",
                detailurl : "news-18320f.html",
                region: "Oceania",
                date : new Date("2020-3-18"),
            },
            {
                heading : "Coronavirus: Australia and New Zealand cancel Anzac Day services",
                imgurl : "img/news-img/news-17320h.jpg",
                detailurl : "news-17320h.html",
                region: "Oceania",
                date : new Date("2020-3-17"),
            },
            {
                heading : "Tom Hanks and Rita Wilson released from coronavirus treatment",
                imgurl : "img/news-img/news-17320i.jpg",
                detailurl : "news-17320i.html",
                region: "Oceania",
                date : new Date("2020-3-17"),
            },
            {
                heading : "Peter Dutton: Australia minister tests positive for virus",
                imgurl : "img/news-img/news-13320e.jpg",
                detailurl : "news-13320e.html",
                region: "Oceania",
                date : new Date("2020-3-13"),
            },
            {
                heading : "",
                imgurl : "img/news-img/news-.png",
                detailurl : "news-.html",
                region: "",
                date : new Date(""),
            },
            {
                heading : "",
                imgurl : "img/news-img/news-.png",
                detailurl : "news-.html",
                region: "",
                date : new Date("2020--"),
            },
            

            
        ]
}

const newsdata = rawdata.data.sort((a, b) => b.date - a.date);
